Repository stemdo-labs/ansible-weekly-exercise-3-3, pull requests merged in 2024-04, with the labels that each got.

#8 #6 Contraseña de profe encriptada
  soluciones/user-management/defaults/README.md
  soluciones/user-management/defaults/secrets.yml
Labels: documentation, feature

#10 4 crear playbook
  auxiliar/Ansible-encryption.png
  soluciones/README.md
  soluciones/playbook.yaml
Labels: documentation

#14 fix: renewing the proyect structure and changing different variables,…
  soluciones/inventory.yml
  soluciones/main_playbook/inventory.ini
  soluciones/main_playbook/playbook_main.yml
  soluciones/test.yml
  soluciones/user_management/.travis.yml
  soluciones/user_management/README.md
  soluciones/user_management/defaults/main.yml
  soluciones/user_management/handlers/main.yml
  soluciones/user_management/inventory.ini
  soluciones/user_management/meta/main.yml
  soluciones/user_management/tasks/create_groups.yml
  soluciones/user_management/tasks/create_users.yml
  soluciones/user_management/tasks/main.yml
  soluciones/user_management/tests/inventory
  soluciones/user_management/tests/test.yml
  soluciones/user_management/vars/main.yml
  soluciones/vars_inventory.yml
Labels: documentation, fix
